name: sheet_loader_localization
description: Download an CSV file and generates the localization keys from an online Google Sheet.
version: 0.3.0
homepage: https://github.com/Hoang-Nguyenn
repository: https://github.com/Hoang-Nguyenn/sheet_loader_localization
issue_tracker: https://github.com/Hoang-Nguyenn/sheet_loader_localization/issues

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  build: ^2.4.0
  build_config: ^1.1.1
  source_gen: ^1.2.6
  http: ^1.2.0
  path: ^1.8.2
  csv: ^6.0.0
  intl: ^0.18.1
  analyzer: ^6.0.0
  file: ^7.0.0
  pub_semver: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
